[theme]
base = "light"
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f3f4"
textColor = "#202124"
font = "sans serif"

[server]
headless = true

[general]
# ✅ Tell Streamlit Cloud where your app script is
target = "surya/scripts/streamlit_app.py"
