# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#1a73e8"        # Google Blue
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f3f4"
textColor = "#202124"
font = "sans serif"
